### ISSUE TITLE
Fargateでwordpressを起動する

### ISSUE THREAD

**Issue by matsumoto-ops** [matsumoto-ops/menta#16]
https://github.com/matsumoto-ops/menta/issues/9
のソースを使ってFargate化する。

**Comment by inamuu** [comment]
@matsumoto-ops 
ステップとしてはネットワーク設定がされていれば、下記流れで出来ればと思います。
少し手間ですがFargateはデバッグが大変なので、１つステップを踏めればと思います。

1. `hello world`が表示できる index.php を配置するDockerfileを作成して、docker-composeを使わずに単体で、PHPが実行できるイメージを作成する。
下記のようにして localhost  にブラウザで接続した際に PHPでhello worldが表示されればOKです。
```
doker run -dti -p 80:80 イメージ名 bash
```

2.  ECRでリポジトリを作成して、ECRに上記イメージをPush
3. Fargateクラスターを作成して、サービスとタスクを定義（その際に上記イメージを指定する, EIPを使用する）
4. エンドポイントへアクセスして、上記hello worldが表示されることを確認する

ここまで出来たら、WordPressを実際に動かす。

1. RDSでDBを作成する
2. Faragteクラスターを別途作成して、WordPressのイメージを指定したサービス、タスクを定義する
3. 上記と同様にエンドポイントへアクセスしてWordPressが表示されるか確認する

一旦ざっくりですが、こんなイメージで出来ればと思います。

**Comment by matsumoto-ops** [comment]
@inamuu 
docker ecsコマンドがリリースされたみたいで、これでやろうと思ってwsl2の設定とかを
昨日やってました。
https://dev.classmethod.jp/articles/docker-ecs/

まだ設定周りがうまくいってないのですが、
dockerhubもdocker-composeを使わずECRで進むほうがよろしいでしょうか？

**Comment by matsumoto-ops** [comment]
@inamuu 
一旦基本通りにすすめます。
fargateフォルダにdockerfileを作りhollo worldが出ることを確認しました。
futureブランチにpushしてあります。

![image](https://user-images.githubusercontent.com/55909058/89098664-7bd9bd80-d424-11ea-87eb-1ea69fdbe6ec.png)

**Comment by inamuu** [comment]
@matsumoto-ops 
お、面白そうですね！どちらでやっていただいても大丈夫です。
私がまだ触ったことがないのでフォローが自信無いですが、そんなに難しそうでも無いのかなという気がしてます。

**Comment by matsumoto-ops** [comment]
面白そうなのですがまずは基本から行こうと思いました。
まずECRに作成したimageを置いてfargate起動してみます。

**Comment by matsumoto-ops** [comment]
@inamuu 
クラスタ・タスク・サービスを作成してhello worldが表示されることを確認しました。
ECSってEC2に出てくると思っていたんですが、EC2コンソールには表示されないんですね。

![image](https://user-images.githubusercontent.com/55909058/89101191-8a31d480-d438-11ea-8add-94b6cff89760.png)
![image](https://user-images.githubusercontent.com/55909058/89101197-9322a600-d438-11ea-91ea-a488259697f1.png)

**Comment by inamuu** [comment]
@matsumoto-ops 
お、早いですね！
ECSの起動方法にもよるのですが、FargateはEC2管理の無いマネージドサービスなのでEC2の表示はありません。
ECSでもEC2を選択した場合は、ECSのところにEC2の表示が出てきますね。

**Comment by matsumoto-ops** [comment]
なるほど。見落としそうで怖いですね。。。

**Comment by matsumoto-ops** [comment]
@inamuu 
wordpressをECSで上げる件ですが、以下Qiitaの記事を見ると速攻終わりそうでした。
基本イメージを使ってdocker-compose.ymlだけで完結してしまいそうなのですが、
RDSとかdockerfileからWordpressイメージを作成する方法で実施した方がいいでしょうか？

https://qiita.com/mymas/items/690f8f778ab09aebaee6

**Comment by inamuu** [comment]
@matsumoto-ops 
そうですね、ご自身で作成したイメージでやっていだければそれ以外はQiitaの手順でも良さそうです！

**Comment by matsumoto-ops** [comment]
@inamuu 
futureブランチに上げました。
ECS以下のdocker-composeを使ってfargate起動できました。
※wordpressのイメージはECRに上げたものを使ってます。
```
1. ecs-cli configure --region ap-northeast-1 --cluster wordpress-cluster
2.ecs-cli up --keypair firtstkey.pem --capability-iam --size 2 --instance-type t2.medium --cluster wordpress-cluster
3.ecs-cli compose -p wordpress --ecs-params ecs-params.yml --cluster wordpress-cluster up  --launch-type FARGATE
```

db接続情報はパラメータストアを使おうと思いましたが、今回は行いませんでした。
- AWS ECS
![image](https://user-images.githubusercontent.com/55909058/89121737-76e83d00-d4fc-11ea-8344-9fdf523d4d2c.png)

- Wordpressログイン後画面
![image](https://user-images.githubusercontent.com/55909058/89121746-85ceef80-d4fc-11ea-9f25-1313c2c997a4.png)

**Comment by matsumoto-ops** [comment]
PR作成したのですが、見覚えのないものがたくさんありました。
これはなんでしょう。。。
![image](https://user-images.githubusercontent.com/55909058/89121904-13f7a580-d4fe-11ea-9638-32d4de914bac.png)

**Comment by inamuu** [comment]
@matsumoto-ops 
速いですね！
流れ的には完了と言って良さそうですね！

Bumpで出ているものは、GitHubがセキュリティアップデートで求めてくるものになります。
設定で有効にしていれば自動的にアップデートができるものをPR作成してくれるので、とりあえず今のところはすべてマージしちゃってOKです。

**Comment by inamuu** [comment]
@matsumoto-ops 
Fargateまで出来たのでしたら、ある程度コンテナについては理解が出来ていると言っても良さそうですがどうでしょうか？
この後の希望の内容はありますか？？

**Comment by matsumoto-ops** [comment]
@inamuu 
dockerをもっと詳しくなりたいのはあるのですが、
言語を覚えたいんですよね。
typescript + 何か（ruby,python,goあたり）
CDKとかansible,terraform等を使ったインフラのコード化とCICDの領域を覚えたいです。

**Comment by inamuu** [comment]
@matsumoto-ops 
なるほど！
そうしたら、折角なので、Terraform, Ansible, CircleCI辺りやってみますか？

- Terraform
  - Terraform を手元から実行出来る環境を作成(backendはS3)
  - Terraform でEC2インスタンスを作成
  - CircleCIを使ってTerraformを実行
- Ansible
  - Ansibleを使って上記で作成したEC2に対してWordPress環境を作成
  - CircleCIを使ってAnsible-lintを実行
   - CircleCIを使ってAnsibleのデプロイ

**Comment by matsumoto-ops** [comment]
@inamuu 
はい！お願いしたいです！

**Comment by inamuu** [comment]
@matsumoto-ops 
ではやりましょう！
またissueを作成してください！
こちらのissueはクローズしていただき、PRはマージOKです。

**Comment by matsumoto-ops** [comment]
@inamuu 
https://github.com/matsumoto-ops/menta/issues/18
を作成しました。
