### ISSUE TITLE
wordpressをcentosイメージから作成

### ISSUE THREAD

**Issue by matsumoto-ops** [matsumoto-ops/menta#5]
- フォルダ構成
docker-compose.yml
　└wordpress - Dockerfile

- 変更点
docker-compose.ymlのwordpress部分を修正
Dockerfileをwordpressイメージからcentosイメージに変更
https://github.com/matsumoto-ops/menta/commit/4b45dc0ed20d28906cb23bded5835b5f6ba2ad53

- 参考URL
https://qiita.com/pedalclecle17/items/6d57d618eab9c3efc82f

- 問題点
`docker-compose up -d ` を実行するとdockerfileから作ったwordpressイメージが
停止してしまう

<pre>
admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta (develop)
$ docker-compose up --build -d
Creating network "menta_default" with the default driver
Building wordpress
Step 1/12 : FROM centos:centos8.1.1911
 ---> 470671670cac
Step 2/12 : RUN /bin/cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
 ---> Using cache
 ---> 50bf35dfe1c3
Step 3/12 : RUN yum install -y epel-release &&    yum clean all
 ---> Using cache
 ---> f47687cc4f30
Step 4/12 : RUN rpm -ivh http://ftp.riken.jp/Linux/remi/enterprise/remi-release-8.rpm
 ---> Using cache
 ---> 402323c6dd7b
Step 5/12 : RUN yum update -y &&    yum clean all
 ---> Using cache
 ---> edb4090d6a01
Step 6/12 : RUN yum -y install httpd &&    yum clean all
 ---> Using cache
 ---> 2b1bd5071e3e
Step 7/12 : RUN yum -y install php74-php php74-php-mysqli php74-php-gd php74-php-mbstring php74-php-opcache php74-php-xml php74-php-pear php74-php-devel php74-php-pecl-imagick php74-php-pecl-imagick-devel php74-php-pecl-zip
 ---> Using cache
 ---> feeceea49f2b
Step 8/12 : RUN ln /usr/bin/php74 /usr/bin/php
 ---> Using cache
 ---> d81e118e4d85
Step 9/12 : RUN chown -R apache:apache /var/www/html
 ---> Using cache
 ---> b7f3d61c2d4f
Step 10/12 : RUN systemctl enable php74-php-fpm
 ---> Using cache
 ---> cb658e74509a
Step 11/12 : RUN systemctl enable httpd
 ---> Using cache
 ---> 65ae3f4465a1
Step 12/12 : EXPOSE 8010
 ---> Using cache
 ---> 2d88cc25a62b
Successfully built 2d88cc25a62b
Successfully tagged menta_wordpress:latest
Creating menta_db_1 ... done
Creating menta_wordpress_1 ... done

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta (develop)
$ docker container ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS
           PORTS                 NAMES
a369e8cfa3eb        menta_wordpress     "/bin/bash"              31 seconds ago      Exited (0) 27 seconds ago                         menta_wordpress_1
1779ee6e494a        mysql:5.7           "docker-entrypoint.s…"   34 seconds ago      Up 31 seconds    
           3306/tcp, 33060/tcp   menta_db_1

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta (develop)
$ docker container start menta_wordpress_1
menta_wordpress_1

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta (develop)
$ docker container ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS
            PORTS                 NAMES
a369e8cfa3eb        menta_wordpress     "/bin/bash"              About a minute ago   Exited (0) 12 seconds ago                         menta_wordpress_1
1779ee6e494a        mysql:5.7           "docker-entrypoint.s…"   About a minute ago   Up About a minute           3306/tcp, 33060/tcp   menta_db_1
</pre>

**Comment by inamuu** [comment]
@matsumoto-ops 
`systemctl` を使われていますが、恐らく動かないかなと思います。
Dockerは権限が分離されており、そのままsystemctlを使おうとするとD-Bus周りでエラーになるんじゃないかと思うので、下記のようにデバッグしてみてください。

１．ベースとなるOSのイメージをbashで起動する。
`docker pull centos:latest`, `docker -p 80:80 run -dti centos:latest /bin/bash` のようにして、bashでアタッチして、そこでDockerfileに記述するコマンドを実行して、うまくいったらメモ、失敗したら違う方法にして、最後にDockerfileに書き起こすようにしてみてください。

あと下記より、各バージョンのリンクをクリックすると、Dockerfileが確認できますので、参考にしつつ出来る限りコピペせずに自分で上述のように試して書き起こして作ってみてください。
※コピペが悪いわけではもちろん無いのですが、ここでデバッグイメージを掴んでいただくと、今後作りたいDockerfileを作るときのデバッグ作業が楽になるかと思います。

https://hub.docker.com/_/wordpress

**Comment by inamuu** [comment]
下記の方も記載されているように、バックグランドで実行した場合は、すぐに終了してしまいます。
逆に言えば、一時的なバッチみたいなのはコンテナに押し込めてDockerで一回実行して終わりという方法も使えます。
今回のようにサービスで動かす場合は、foreground で動かす OR 別のプロセスをforegroundで動かす方法があります。
https://teratail.com/questions/174657

**Comment by matsumoto-ops** [comment]
手でdockerfileの中身を叩いてみたんですが特にエラーは発生しませんでした。
<pre>
[root@a1406927b624 /]# ln /usr/bin/php74 /usr/bin/php
[root@a1406927b624 /]# 
[root@a1406927b624 /]#
[root@a1406927b624 /]# chown -R apache:apache /var/www/html
[root@a1406927b624 /]# ls -al /var/www/   
total 20
drwxr-xr-x 4 root   root   4096 Jul 23 16:17 .
drwxr-xr-x 1 root   root   4096 Jul 23 16:17 ..
drwxr-xr-x 2 root   root   4096 Jun  9 05:16 cgi-bin
drwxr-xr-x 2 apache apache 4096 Jun  9 05:16 html
[root@a1406927b624 /]# systemctl enable php74-php-fpm
Created symlink /etc/systemd/system/multi-user.target.wants/php74-php-fpm.service → /usr/lib/systemd/system/php74-php-fpm.service.
[root@a1406927b624 /]# systemctl enable httpd
Created symlink /etc/systemd/system/multi-user.target.wants/httpd.service → /usr/lib/systemd/system/httpd.service.
[root@a1406927b624 /]#
</pre>

ただコンテナにログインしてsystemctlコマンドを実行するとご指摘の通りエラーが出ています。
```
[root@a1406927b624 /]# systemctl status httpd
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[root@a1406927b624 /]#
```

最初のコマンドが通ってしまう理由は何なのでしょうか。

**Comment by inamuu** [comment]
@matsumoto-ops 
systemctlの細かいシステムコールは把握していませんが、サブコマンドでenableを指定したときは、単にシンボリックリンクを作成しているだけなので、エラーにならないのかなと思いました。
サービスとして起動しようとするとやはり落ちてしまうのかなと思います。

**Comment by matsumoto-ops** [comment]
```
$ docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS
   PORTS                 NAMES
a385c0a2319c        menta_wordpress     "/bin/sh -c '/usr/sb…"   20 minutes ago      Up 20 minutes    
   8010/tcp              menta_wordpress_1
2b7652362fa2        mysql:5.7           "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes    
   3306/tcp, 33060/tcp   menta_db_1
```
systemctlを止めて、`ENTRYPOINT /usr/sbin/httpd -D FOREGROUND` 
にしたことでwordpressのコンテナも動くようになりました。
docker-compose buildをし忘れていたせいで修正が反映されず無駄に時間がかかってました。

ただlocalhost:8010でブラウザからアクセスできず、ここの確認がまだです。
![image](https://user-images.githubusercontent.com/55909058/88315188-f0d83380-cd50-11ea-9cf3-31d3041739fa.png)

修正コード：
https://github.com/matsumoto-ops/menta/commit/f3d2a694c4f401920f329710b2d6b9070f5de8d3

**Comment by matsumoto-ops** [comment]
こちら立ち上げれたのですが、apacheの画面が起動してしまいました。
よく見るとwordpressを入れてないように見えるので、
https://github.com/docker-library/wordpress/blob/def14e3e6e6a376dcfb856f9eb542e3e399457af/php7.2/fpm/Dockerfile
のdockerfileを作ってwordpressブランチで進めていこうと思います。

**Comment by matsumoto-ops** [comment]
wordpressブランチからdevelopブランチに戻しました。
php:7.2-fpmのイメージだとapacheが入っておらず、起動できなかったので
php:7.2-apacheのイメージに切り替えて実施しています。
参考にしたURL
https://html-coding.co.jp/knowhow/environment/docker_wp/

ただ上記URL通りにやると
`error: /usr/src/php/ext/libxml2 does not exist`
のエラーが出てしまいます。libxml2をインストールすればいいのかと思い
参考URL2の通りに実行してみるとこれはこれでエラーが出てしまいます。
```
Step 6/12 : RUN docker-php-ext-install     mbstring     json     simplexml     dom     fileinfo     hash     libxml2     libxml2-devel     xml     iconv
 ---> Running in 0a88b8d33d3b
error: /usr/src/php/ext/libxml2 does not exist

usage: /usr/local/bin/docker-php-ext-install [-jN] [--ini-name file.ini] ext-name [ext-name ...]      
   ie: /usr/local/bin/docker-php-ext-install gd mysqli
       /usr/local/bin/docker-php-ext-install pdo pdo_mysql
       /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop

if custom ./configure arguments are necessary, see docker-php-ext-configure

Possible values for ext-name:
bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl json ldap mbstring mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap sockets sodium spl standard sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zend_test zip

Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.
ERROR: Service 'wordpress' failed to build: The command '/bin/sh -c docker-php-ext-install     mbstring     json     simplexml     dom     fileinfo     hash     libxml2     libxml2-devel     xml     iconv' returned a non-zero code: 1
```

参考URL2:
https://stackoverflow.com/questions/47671108/docker-php-ext-install-mcrypt-missing-folder

ちょっと自力で解決できそうにないのでご支援頂けますでしょうか。

コミット：
77dec289721da067c3e4f3504e188edb8b21f5bd

**Comment by matsumoto-ops** [comment]
https://github.com/docker-library/wordpress/tree/master/php7.4/fpm

で作成しています。phpmyadminのコンテナも追加しました。
phpmyadminにはアクセスできるのですが、肝心のwordpressには
アクセスができません。
wordpressコンテナにapacheもしくはnginxがたってないからでしょうか？


```
admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta (develop)
$ docker-compose up -d
Creating network "menta_default" with the default driver
Creating menta_db_1 ... done
Creating menta_wordpress_1  ... done
Creating menta_phpmyadmin_1 ... done

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta (develop)
$ docker logs menta_wordpress_1 
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html

MySQL "CREATE DATABASE" Error: Access denied for user 'wordpress'@'%' to database 'wordpressdb'

WARNING: unable to establish a database connection to 'db:3306'
  continuing anyways (which might have unexpected results)

[25-Jul-2020 11:36:57] NOTICE: fpm is running, pid 1
[25-Jul-2020 11:36:57] NOTICE: ready to handle connections

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta (develop)
```
![image](https://user-images.githubusercontent.com/55909058/88456189-9fe24f80-ceb6-11ea-9566-37b1b8849cf3.png)

**Comment by inamuu** [comment]
@matsumoto-ops 
今の状態で確認してみたいので一度PRを作成いただけますでしょうか。
あと、メンションをしてもらえると助かります。

**Comment by inamuu** [comment]
下記についてですが、socket対応されたようなコミットを見ましたが、socket通信になっていないようでした。
また、apacheも起動していないように見受けられるので、まずはbashでattachして、そこで正しく動くところまでやってみてください。
https://github.com/matsumoto-ops/menta/pull/6#issuecomment-664002370
正しく動くというのは、ブラウザからアクセスできる状態まで、つまり`ps aux` などで、apacheもphp-fpmも動いている状態で、`netstat -lntp` or `ss lntp` などで80番ポート待ち受けまでするようにしてからDockerfileに落とし込む流れになります。
Dockerfileだけで作っていくと毎回ビルドで時間がかかってしまい、効率が悪くなってしまいますので、コンテナでコマンドやファイルをメモして、うまくいったものをDockerfileに落とし込んでいくようにすると良いかと思います。

**Comment by inamuu** [comment]
@matsumoto-ops 
以前Apacheをフォアグランドで起動するようにお伝えしたと思うのですが、どこに反映されてますでしょうか。
また、unix domain socketもmasterには反映されていないようですので、そちらも反映いただけますでしょうか。
php-fpmを起動した際に socketファイルが作成されていることを確認してください。
www.confで指定したファイルです。
その後に、apacheをフォアグランドで起動して、その状態でcurl, ブラウザ何でも良いのでアクセスできるかをご確認ください。
下記のようなphpinfo.phpファイルを配置して、Apacheからアクセスして、phpが動くことを確認もしてみてください。
```php
<?php
phpinfo();
?>
```

**Comment by inamuu** [comment]
ここはWordPressのDB名がMySQLで指定しているところと一致していないので、一致するようにした方が良いですね。
https://github.com/matsumoto-ops/menta/blob/master/docker-compose.yml#L37

**Comment by inamuu** [comment]
@matsumoto-ops 
docker-compose up -d をすると下記のようにエラーになってしまっているので、エラーを解消しないとですね。
docker-entrypoint.shはfile not foundになってしまっているので、実行出来ていません。

```
WARNING: Image for service wordpress was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating menta_db_1 ... done
Creating menta_wordpress_1  ... error
Creating menta_phpmyadmin_1 ... done

ERROR: for menta_wordpress_1  Cannot start service wordpress: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown

ERROR: for wordpress  Cannot start service wordpress: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by matsumoto-ops** [comment]
@inamuu 
ありがとうございます。
よく見るとイメージにapacheがそもそも入ってなかったですね。
futureブランチを作ってそっちで進めていこうと思います。

**Comment by matsumoto-ops** [comment]
@inamuu 

futureブランチに切りなおしました
https://github.com/matsumoto-ops/menta/tree/future/wordpress

wordpressフォルダ下のdockerfileをbuildするとimageはできるのですが
このイメージを起動できません。

```
$ docker image build -t wordpress-test .
Sending build context to Docker daemon  10.75kB
Step 1/13 : FROM php:7.2-apache
 ---> 245a85bd2420
Step 2/13 : RUN apt-get update && apt-get -y install git
 ---> Using cache
 ---> 3207479c2c8e
Step 3/13 : RUN apt-get -q -y install default-mysql-client
 ---> Using cache
 ---> 9e23d2463daf
Step 4/13 : RUN docker-php-ext-install pdo_mysql mysqli
 ---> Using cache
 ---> 4fe76219c4c8
Step 5/13 : RUN apt-get update && apt-get install -y     libmcrypt-dev     libxml2     libxml2-dev    
 && pecl install mcrypt-1.0.2     && docker-php-ext-enable mcrypt
 ---> Using cache
 ---> 52d09463e788
Step 6/13 : RUN docker-php-ext-install     mbstring     json     simplexml     dom     fileinfo     hash     xml     iconv
 ---> Using cache
 ---> c4f86e8b455a
Step 7/13 : RUN apt-get install -y     libfreetype6-dev     libjpeg62-turbo-dev     libmcrypt-dev     
libpng-dev     mailutils     memcached     msmtp     msmtp-mta     openssl     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install 
-j$(nproc) gd exif
 ---> Using cache
 ---> 9dcd86e9aa81
Step 8/13 : VOLUME /var/www/html
 ---> Using cache
 ---> 8b3b6fbb10ed
Step 9/13 : RUN mkdir /var/run/php-fpm
 ---> Using cache
 ---> ac2b109e51b2
Step 10/13 : COPY docker-entrypoint.sh /usr/local/bin/
 ---> Using cache
 ---> 07fc033175b5
Step 11/13 : ENTRYPOINT ["docker-entrypoint.sh"]
 ---> Using cache
 ---> c028ace29b5d
Step 12/13 : CMD ["/usr/sbin/apache2", "-D",  "FOREGROUND"]
 ---> Using cache
 ---> fcab024f1d48
Step 13/13 : EXPOSE 80
 ---> Using cache
 ---> 7fe72ba1b347
Successfully built 7fe72ba1b347
Successfully tagged wordpress-test:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All 
files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to 
double check and reset permissions for sensitive files and directories.
```
```
$ docker image ls | grep wordpress-test
wordpress-test                                                          latest
                   7fe72ba1b347        18 minutes ago      652MB
$ docker container run wordpress-test
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

起動に失敗したコンテナをimageにして起動しようとしても同様のエラーとなります。
```
$ docker container ls -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS
          PORTS               NAMES
d3a582e5795f        wordpress-test      "docker-entrypoint.s…"   7 minutes ago       Exited (1) 7 minutes ago                       confident_mestorf

$ docker commit d3a582e5795f docker-test
sha256:c76d459e7f7ad43b6ece40009721d18d0e934b693b398b907fc5b24de1b76d34

$ docker run --rm -it docker-test bash
standard_init_linux.go:211: exec user process caused "no such file or directory"
failed to resize tty, using default size
```

検索をすると以下二点が原因との記載がありました。
- 改行コードがCRLFになっている
- alpine linuxはbashが使えない
https://qiita.com/kabik/items/5591f62c0ef6ddef5db2
https://qiita.com/SSM3G/items/7ce820f6611213f9e1d6

ただshでつなごうとしても繋げず、原因が分からない状態です。
```
$ docker run --rm -it docker-test sh
standard_init_linux.go:211: exec user process caused "no such file or directory"
failed to resize tty, using default size
```

どこに問題があるのかご確認頂けませんでしょうか。

**Comment by inamuu** [comment]
@matsumoto-ops 
確認します 🙆‍♂️

**Comment by inamuu** [comment]
@matsumoto-ops 
docker-entrypoint.shに実行権限が付与されていないことが原因でした。
`chmod u+x docker-entrypoint.sh`
して、再度ビルドしてあげれば、コンテナが起動しますのでご確認ください。

**Comment by matsumoto-ops** [comment]
@inamuu 
`RUN chmod u+x /usr/local/bin/docker-entrypoint.sh`
を追加して再ビルドしたのですが
```
admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta/wordpress (future)
$ docker container run wordpress-test
standard_init_linux.go:211: exec user process caused "no such file or directory"

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta/wordpress (future)
$ docker container ls -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS
           PORTS               NAMES
a1cc4d66b373        wordpress-test      "docker-entrypoint.s…"   26 seconds ago      Exited (1) 23 seconds ago                       gallant_montalcini
```
となり起動しません。

**Comment by inamuu** [comment]
@matsumoto-ops 
docker-compose.yml でwordpressに `command: apachectl -D FOREGROUND` を追加してみてください。
docker-entrypoint.sh で`no such file or directory` になる原因がパッとわからないですが、$PATHが読めてないのかもです。
そのままだとApacheが起動できていないようなので上記をdocker-compose.ymlで上書きすることでいけるかと思います。

http://localhost:8081/phpinfo.php

```diff
  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress
      dockerfile: Dockerfile
++  command: apachectl -D FOREGROUND
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    links:
      - db
    ports:
      - "8081:80"
```

これで動いたら、docker-compose.yml

**Comment by matsumoto-ops** [comment]
@inamuu 
ありがとうございます。後でやってみます。

こちらで確認していたところ、文字コードのせいだったかもしれません。
```
$ docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS
   PORTS               NAMES
56ccb8fd2514        wordpress-test2     "docker-php-entrypoi…"   5 minutes ago       Up 5 minutes     
   80/tcp              dreamy_tharp

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta/wordpress (future)
$ docker cp docker-entrypoint.sh 56ccb8fd2514:/usr/local/bin/

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta/wordpress (future)
$ docker exec -it 56ccb8fd2514 sh
# ls -l /usr/local/bin
total 27392
-rwxrwxr-x 1 root root     1346 Jul 22 11:01 apache2-foreground
-rwxr-xr-x 1 root root      199 Jul 27 17:03 docker-entrypoint.sh
-rwxrwxr-x 1 root root      133 Jul 22 11:01 docker-php-entrypoint
-rwxrwxr-x 1 root root     1449 Jul 22 11:01 docker-php-ext-configure
-rwxrwxr-x 1 root root     2668 Jul 22 11:01 docker-php-ext-enable
-rwxrwxr-x 1 root root     2506 Jul 22 11:01 docker-php-ext-install
-rwxrwxr-x 1 root root      587 Jul 22 11:01 docker-php-source
-rwxr-xr-x 1 root root       41 Jul 22 11:06 freetype-config
-rwxr-xr-x 1 root root      817 Jul 22 11:06 pear
-rwxr-xr-x 1 root root      838 Jul 22 11:06 peardev
-rwxr-xr-x 1 root root      751 Jul 22 11:06 pecl
lrwxrwxrwx 1 root root        9 Jul 22 11:06 phar -> phar.phar
-rwxr-xr-x 1 root root    14817 Jul 22 11:06 phar.phar
-rwxr-xr-x 1 root root 13920664 Jul 22 11:06 php
-rwxr-xr-x 1 root root     2780 Jul 22 11:06 php-config
-rwxr-xr-x 1 root root 14052256 Jul 22 11:06 phpdbg
-rwxr-xr-x 1 root root     4534 Jul 22 11:06 phpize
# /usr/local/bin/docker-entrypoint.sh
sh: 2: /usr/local/bin/docker-entrypoint.sh: not found
# cat -A /usr/local/bin/docker-entrypoint.sh
#!/bin/sh^M$
^M$
if [ ! -d "/tmp/check" ]; then^M$
  mkdir /tmp/check^M$
  echo `date` > /tmp/check/first_`date +%Y%m%d_%H%M%S`^M$
else^M$
  echo `date` > /tmp/check/second_`date +%Y%m%d_%H%M%S`^M$
fi^M$
^M$
exec "$@"#
# 
# tr -d '\r' test.sh
tr: extra operand 'test.sh'
Only one string may be given when deleting without squeezing repeats.
Try 'tr --help' for more information.
# tr -d '\r' /usr/local/bin/docker-entrypoint.sh
tr: extra operand '/usr/local/bin/docker-entrypoint.sh'
Only one string may be given when deleting without squeezing repeats.
Try 'tr --help' for more information.
# ^C
# exit
```
docker-entrypoint.sh
を開いてみたらCRLFになっていたのでLFに直して上げなおしたらshが実行できました。

```
admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta/wordpress (future)
$ docker cp docker-entrypoint.sh 56ccb8fd2514:/usr/local/bin/

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta/wordpress (future)
$

admin@home-pc MINGW64 ~/OneDrive/work/menta/wordpress/menta/wordpress (future)
$ docker exec -it 56ccb8fd2514 sh
# 
# /usr/local/bin/docker-entrypoint.sh
# 
```
参考サイト
https://qiita.com/b4b4r07/items/9ea50f9ff94973c99ebe


このコマンドを打つとgit に上げるときにcrlfをlfに自動変換してくれるのだと思ってましたが違ったようですね。。
```
git config --global core.autocrlf input
```

**Comment by inamuu** [comment]
おーなるほど。。文字コードでしたか。気が付きませんでした 💦 
autocrlfで効果ありそうですが、globalになっているので、localではfalseになっているとか？？？ 🤔

**Comment by matsumoto-ops** [comment]
@inamuu 
`git config --global core.autocrlf input`
はgitに上げるときに勝手にcrlfにするのを防ぐだけっぽいですね。
僕の環境がwindowsなので作成時にcrlfになってしまっていたみたいです。

先に進めようと思ったら以下のエラーが発生しました。

```
$ docker container run  wordpress-test3
[Thu Jul 30 05:25:53.687486 2020] [core:warn] [pid 1] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
apache2: Syntax error on line 80 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot
```

https://www.it-swarm.dev/ja/server/ubuntu-apache2-defaultruntimedir%e3%81%af%e3%80%81serverroot%e3%81%ab%e5%af%be%e3%81%97%e3%81%a6%e7%b5%b6%e5%af%be%e3%81%be%e3%81%9f%e3%81%af%e7%9b%b8%e5%af%be%e3%81%ae%e6%9c%89%e5%8a%b9%e3%81%aa%e3%83%87%e3%82%a3%e3%83%ac%e3%82%af%e3%83%88%e3%83%aa%e3%81%a7%e3%81%82%e3%82%8b%e5%bf%85%e8%a6%81%e3%81%8c%e3%81%82%e3%82%8a%e3%81%be%e3%81%99/961150067/
を参考に
`/etc/Apache2/envvars`
を見てみた結果を添付しました。
```
: ${APACHE_RUN_DIR:=/var/run/apache2$SUFFIX}
export APACHE_RUN_DIR
```
となっているのですが、これをdockerfileの
CMD ["/usr/sbin/apache2", "-D",  "FOREGROUND"]
に合わせて/usr/sbin/apache2にすればいいのでしょうか。

動作がよく分からずご教授頂きたいです。

[envvars.txt](https://github.com/matsumoto-ops/menta/files/4999540/envvars.txt)

**Comment by inamuu** [comment]
@matsumoto-ops 
おや？文字コードの部分だけ問題なければ、あとはdocker-compose側で下記のように修正いただいて、後は `docker-compose up -d` で動くかなと思うのですがいかがでしょうか？
一応私のほうで `future` ブランチをcloneして、下記修正を入れたらphpinfoは表示出来ました。
https://github.com/matsumoto-ops/menta/issues/5#issuecomment-666111938

**Comment by matsumoto-ops** [comment]
@inamuu 
↑でコメント頂いたところを修正してfutureブランチにpushしました。

futureブランチを再度cloneしてdocker-composeを実行したのですが
アクセス権の問題でエラーになります。。。
```
admin@home-pc MINGW64 /c/work/menta (future)
$ curl localhost:8081
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at localhost Port 8081</address>
</body></html>

admin@home-pc MINGW64 /c/work/menta (future)
$ docker exec -ti menta_wordpress_1 bash


root@ff2997e0ab1f:/var/www/html# ls
phpinfo.php
root@ff2997e0ab1f:/var/www/html# ls -l
total 4
-rwxr-xr-x 1 root root 19 Jul 30 05:23 phpinfo.php
root@ff2997e0ab1f:/var/www/html# curl localhost:80 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at localhost Port 80</address>
</body></html>
```

**Comment by inamuu** [comment]
@matsumoto-ops 
phpinfo.phpなのでそのままではアクセス出来ないのと、docker-compose.ymlでwordpressは8081にされていたとおもうので、下記ではいかがでしょうか。

http://localhost:8081/phpinfo.php

**Comment by matsumoto-ops** [comment]
@inamuu 
表示されました！
確かにドキュメントルートにはphpinfo.phpしか置いてなかったですね。

**Comment by inamuu** [comment]
@matsumoto-ops 
良かったです 🎉 🎉 🎉

**Comment by inamuu** [comment]
@matsumoto-ops 

そしたら、次は下記流れでやっていきましょう！
このissueは長くなったのと１つ達成しましたので、別issueをたてましょうか。

### 次のステップ
WordPressのソースをdocker-compose.ymlのVolumeでマウントしてみてください。
そうすると、手元にソースコードを置いた状態で、Dockerを使って開発が出来るようになります。
これでDockerの基本開発部分のイメージがつくかと思います。
※私が在籍していた会社2社とも上記のやり方をベースとして開発環境を用意していました。

### その次のステップ
それが出来たら、WordPressのソースコードをコンテナにコピーするようにしてみます。
これは、上記と異なり、手元の開発用ではなくてコンテナホストで動かすイメージを作ることになります。

**Comment by matsumoto-ops** [comment]
@inamuu 
ではこれはCloseして新しいissueを作成します。
今回のPRを作成したのですが、これはMergeしてしまってよろしいでしょうか。
https://github.com/matsumoto-ops/menta/pull/8
