### ISSUE TITLE
WordPressのソースをdocker-compose.ymlのVolumeでマウントする

### ISSUE THREAD

**Issue by matsumoto-ops** [matsumoto-ops/menta#9]
#5  の次のステップ
WordPressのソースをdocker-compose.ymlのVolumeでマウントしてみてください。
そうすると、手元にソースコードを置いた状態で、Dockerを使って開発が出来るようになります。
これでDockerの基本開発部分のイメージがつくかと思います。
※私が在籍していた会社2社とも上記のやり方をベースとして開発環境を用意していました。

その次のステップ
それが出来たら、WordPressのソースコードをコンテナにコピーするようにしてみます。
これは、上記と異なり、手元の開発用ではなくてコンテナホストで動かすイメージを作ることになります。
EKSでも良いですが、たとえばAWSのFargateとかでも使えるものにできるかと思います。

**Comment by matsumoto-ops** [comment]
@inamuu 
#5 でdocker-compose.ymlを使ってwordpressが立つようになったと思うのですが、
WordPressのソースは何を指していますでしょうか。
docker-compose.ymlのwordpressをmysqlみたいな感じにするということでしょうか？
ちょっとイメージがわかず。。

**Comment by inamuu** [comment]
@matsumoto-ops 
以前やった際に下記のようにzipでダウンロードするようにしていたと思います。
今回はこちらに下記のようなWordPressのソースコードが含まれていないので、phpinfo.phpでPHPが動くところまでは確認いただけました。
https://github.com/matsumoto-ops/menta/pull/8/files#diff-8cc3d1a44ca0b6c12be55b12bd1965f1L79

今度はcurlで取ってくるのではなく、このリポジトリにWordPressのソースコードを含めて、docker-composeでvolumeマウントするようにしてみてください。
手元の開発環境でWordPress（PHPアプリケーション）の開発できるようになるのが目的となります 👍

**Comment by inamuu** [comment]
@matsumoto-ops 
Dockerfileとdocker-compose.ymlは別物と考えてもらえればと思います。
docker-composeはbuildを実行してから、volumeマウントしたり、commandを実行します。
そのためDockerile上でwordpress.tar.gzをCOPYしなければ、存在しない状態ので、No such file or directoryとなってしまいます。
やるのでしたら、最初から解凍してしまって、Dockerfileでtarで展開しなくても今回においてはいいかなと思います。
次のステップではCOPYでコピーする必要がありますが。
ベースをDockerfileで作って、すでに展開されたソースをvolumeでマウントするイメージですね。

**Comment by inamuu** [comment]
@matsumoto-ops 
これは私が前に試したRailsの開発環境ですが、こんなイメージです。
https://github.com/inamuu/rails_sample_app/tree/master/test_app_docker

**Comment by matsumoto-ops** [comment]
@inamuu 
つまりdocker-compose.ymlのボリューム連結は最後に行われるという理解で正しいですか？

**Comment by inamuu** [comment]
@matsumoto-ops 
はい、正しいです！

**Comment by matsumoto-ops** [comment]
@inamuu 
なるほど。腑に落ちました。
解凍したwordpressをsrcに置き、/var/www/htmlにvolumeをマウントさせて
wordpressが起動しました。
今futureブランチにpushしましたのでご確認頂けますでしょうか。

**Comment by matsumoto-ops** [comment]
一旦動作はしたのでpull reqestを作成しました。
https://github.com/matsumoto-ops/menta/pull/10

**Comment by inamuu** [comment]
@matsumoto-ops 
ですね！issueも別にしましょう！

**Comment by matsumoto-ops** [comment]
https://github.com/matsumoto-ops/menta/issues/16
を作成しました。
